export const data = [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publication_year: 1960,
        genre: ["Fiction", "Classic"],
        description: "A classic novel depicting racial injustice in the American South.",
        cover_image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSZXRzEBJHBDv1vNlkUO-yBvkBTXXYUE1K0ptQLvopWQFNn3W7F",
      },
      {
        id: 2,
        title: "1984",
        author: "George Orwell",
        publication_year: 1949,
        genre: ["Dystopian", "Science Fiction"],
        description: "A dystopian novel portraying a totalitarian society.",
        cover_image: "https://m.media-amazon.com/images/I/61ZewDE3beL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 3,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        publication_year: 1813,
        genre: ["Romance", "Classic"],
        description: "A story of love and misunderstandings in 19th-century England.",
        cover_image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/book/f/s/1/pride-prejudice-original-imagy32ephewfga2.jpeg?q=20&crop=false",
      },
      {
        id: 4,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        publication_year: 1925,
        genre: ["Fiction", "Classic"],
        description: "A novel about the American Dream and tragic love.",
        cover_image: "https://images.booksense.com/images/494/260/9782382260494.jpg",
      },
      {
        id: 5,
        title: "Moby Dick",
        author: "Herman Melville",
        publication_year: 1851,
        genre: ["Adventure", "Classic"],
        description: "The epic tale of a sailor's pursuit of a white whale.",
        cover_image: "https://m.media-amazon.com/images/I/71d5wo+-MuL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 6,
        title: "War and Peace",
        author: "Leo Tolstoy",
        publication_year: 1869,
        genre: ["Historical", "Classic"],
        description: "A sweeping novel of Russian society during the Napoleonic era.",
        cover_image: "https://rekhtabooks.com/cdn/shop/products/9788175992832.jpg?v=1688454306",
      },
      {
        id: 7,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publication_year: 1951,
        genre: ["Fiction", "Classic"],
        description: "A story of teenage angst and alienation.",
        cover_image: "https://m.media-amazon.com/images/I/7108sdEUEGL.jpg",
      },
      {
        id: 8,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        publication_year: 1937,
        genre: ["Fantasy", "Adventure"],
        description: "The adventure of Bilbo Baggins in Middle-earth.",
        cover_image: "https://m.media-amazon.com/images/I/71jKeGU9nKL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 9,
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        publication_year: 1866,
        genre: ["Psychological", "Classic"],
        description: "A deep exploration of guilt and redemption.",
        cover_image: "https://m.media-amazon.com/images/I/71O2XIytdqL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 10,
        title: "Brave New World",
        author: "Aldous Huxley",
        publication_year: 1932,
        genre: ["Dystopian", "Science Fiction"],
        description: "A vision of a future controlled by technology and conformity.",
        cover_image: "https://m.media-amazon.com/images/I/81fiJzvcB2L._UF1000,1000_QL80_.jpg",
      },
      {
        id: 11,
        title: "The Alchemist",
        author: "Paulo Coelho",
        publication_year: 1988,
        genre: ["Fiction", "Philosophical"],
        description: "A fable about following your dreams and finding treasure.",
        cover_image: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 12,
        title: "Anna Karenina",
        author: "Leo Tolstoy",
        publication_year: 1878,
        genre: ["Romance", "Classic"],
        description: "A tragic love story set in Russian high society.",
        cover_image: "https://m.media-amazon.com/images/I/71O3PTUA3vL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 13,
        title: "The Odyssey",
        author: "Homer",
        publication_year: -800,
        genre: ["Epic", "Classic"],
        description: "The legendary journey of Odysseus returning home.",
        cover_image: "https://m.media-amazon.com/images/I/A1JR2oK-orL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 14,
        title: "One Hundred Years of Solitude",
        author: "Gabriel Garcia Marquez",
        publication_year: 1967,
        genre: ["Magical Realism", "Classic"],
        description: "The multi-generational story of the Buendia family.",
        cover_image: "https://m.media-amazon.com/images/I/81oAEEwxBWL.jpg",
      },
      {
        id: 15,
        title: "Les Misérables",
        author: "Victor Hugo",
        publication_year: 1862,
        genre: ["Historical", "Classic"],
        description: "The struggles of the poor in 19th-century France.",
        cover_image: "https://m.media-amazon.com/images/I/91M5Tm97jEL._UF1000,1000_QL80_.jpg",
      },
      {
        id: 16,
        title: "The Divine Comedy",
        author: "Dante Alighieri",
        publication_year: 1320,
        genre: ["Epic", "Classic"],
        description: "An allegorical journey through Hell, Purgatory, and Paradise.",
        cover_image: "https://m.media-amazon.com/images/I/51i-9SGWr-L._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 17,
        title: "The Iliad",
        author: "Homer",
        publication_year: -750,
        genre: ["Epic", "Classic"],
        description: "The tale of the Trojan War and its heroes.",
        cover_image: "https://m.media-amazon.com/images/I/91UYfGjbZsL.jpg",
      },
      {
        id: 18,
        title: "Jane Eyre",
        author: "Charlotte Bronte",
        publication_year: 1847,
        genre: ["Romance", "Classic"],
        description: "The story of a governess and her complex love.",
        cover_image: "https://m.media-amazon.com/images/I/61N-UOA0alL._UF1000,1000_QL80_.jpg",
      },
      {
        id: 19,
        title: "Frankenstein",
        author: "Mary Shelley",
        publication_year: 1818,
        genre: ["Horror", "Science Fiction"],
        description: "A scientist's creation turns into a monster.",
        cover_image: "https://m.media-amazon.com/images/I/81TVqiv-ctL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 20,
        title: "Wuthering Heights",
        author: "Emily Bronte",
        publication_year: 1847,
        genre: ["Romance", "Classic"],
        description: "A dark tale of love and revenge.",
        cover_image: "https://m.media-amazon.com/images/I/81unikMK30L._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 21,
        title: "Dracula",
        author: "Bram Stoker",
        publication_year: 1897,
        genre: ["Horror", "Classic"],
        description: "The legendary vampire tale.",
        cover_image: "https://m.media-amazon.com/images/I/61lpCBN58DL._AC_UF1000,1000_QL80_.jpg",
      },
      {
        id: 22,
        title: "Wuthering Heights",
        author: "Emily Brontë",
        publication_year: 1847,
        genre: ["Classic", "Gothic"],
        description: "A tale of intense love and revenge on the Yorkshire moors.",
        cover_image: "https://m.media-amazon.com/images/I/81unikMK30L._AC_UF1000,1000_QL80_.jpg"
      },
      {
        id: 23,
        title: "The Scarlet Letter",
        author: "Nathaniel Hawthorne",
        publication_year: 1850,
        genre: ["Classic", "Historical Fiction"],
        description: "A novel about sin, guilt, and redemption in Puritan America.",
        cover_image: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781627939911/the-scarlet-letter-9781627939911_hr.jpg"
      },
      {
        id: 24,
        title: "Frankenstein",
        author: "Mary Shelley",
        publication_year: 1818,
        genre: ["Gothic", "Science Fiction"],
        description: "A story about the consequences of playing God by creating life.",
        cover_image: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982146177/frankenstein-9781982146177_hr.jpg"
      },
      {
        id: 25,
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        publication_year: 1847,
        genre: ["Classic", "Romance"],
        description: "A novel about the struggles of an orphaned girl and her journey to independence.",
        cover_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShCDskdFWmvcNwtPMeqfzB5ZHRj1q0LPS0Zw&s"
      },
      {
        id: 26,
        title: "The Old Man and the Sea",
        author: "Ernest Hemingway",
        publication_year: 1952,
        genre: ["Fiction", "Adventure"],
        description: "A short novel about an epic battle between an old fisherman and a giant marlin.",
        cover_image: "https://upload.wikimedia.org/wikipedia/en/7/73/Oldmansea.jpg"
      },
      {
        id: 27,
        title: "Of Mice and Men",
        author: "John Steinbeck",
        publication_year: 1937,
        genre: ["Fiction", "Tragedy"],
        description: "A story about two displaced ranch workers struggling for their dream during the Great Depression.",
        cover_image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/OfMiceAndMenPoster.jpg/220px-OfMiceAndMenPoster.jpg"
      },
      {
        id: 28,
        title: "Fahrenheit 451",
        author: "Ray Bradbury",
        publication_year: 1953,
        genre: ["Dystopian", "Science Fiction"],
        description: "A dystopian novel about a future society where books are outlawed and burned.",
        cover_image: "https://schicksalgemeinschaft.wordpress.com/wp-content/uploads/2015/10/fahrenheit-451.jpg"
      },
      {
        id: 29,
        title: "The Grapes of Wrath",
        author: "John Steinbeck",
        publication_year: 1939,
        genre: ["Classic", "Historical Fiction"],
        description: "A novel about the struggles of migrant workers during the Great Depression.",
        cover_image: "https://resizing.flixster.com/vHzXH-SBQwLAXtgmpfjAqsJW-q4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p3554_v_v10_ab.jpg"
      },
      {
        id: 30,
        title: "Dracula",
        author: "Bram Stoker",
        publication_year: 1897,
        genre: ["Horror", "Gothic"],
        description: "A Gothic horror novel about the infamous vampire Count Dracula.",
        cover_image: "https://m.media-amazon.com/images/M/MV5BZGVlYTdhYzQtYWVmMi00OTJmLTkyYmYtMWRiMTgyMmY2MjEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
      }
  ];
  